Repository masisikip/MoneyMo, pull requests merged in 2025-02, with the labels that each got.

#9 [docs] create contributing.md
  CONTRIBUTING.md
  README.md
Labels: Documentation, Good first issue

#38 [feat] Connect db
  api/includes/authenticate.php
  api/includes/connect-db.php
  api/includes/load-env.php
Labels: Feature

#41 [docs] update contributing in README to remove fork step
  README.md
Labels: Documentation

#44 [feat] [core]User auth
  api/includes/authenticate.php
  api/includes/connect-db.php
  public/login/index.php
Labels: Feature

#51 User management page
  public/css/styles.css
  public/user.php
  public/views/logic/user_add.php
  public/views/logic/user_admin_edit.php
  public/views/logic/user_delete.php
Labels: Page, Admin

#53 Item management page
  public/item.php
  public/views/logic/item_create.php
  public/views/logic/item_delete.php
  public/views/logic/item_update.php
Labels: Page, Admin

#50 [docs] Remove Git conventional commit format and update PR template i…
  CONTRIBUTING.md
Labels: Documentation

#57 Improve item page
  public/css/styles.css
  public/item.php
Labels: Enhancement, Admin
