Repository masisikip/MoneyMo, pull requests merged in 2025-03, with the labels that each got.

#65 [Deprecation] deprecation of api, fix includes
  api/includes/authenticate.php
  api/index.php
  docs/api/index.md
  docs/interface/index.md
  public/admin/index.php
  public/includes/connect-db.php
  public/includes/connect.php
  public/includes/load-env.php
  public/item.php
  public/user.php
  public/views/logic/item_create.php
  public/views/logic/item_delete.php
  public/views/logic/item_update.php
  public/views/logic/user_add.php
  public/views/logic/user_admin_edit.php
  public/views/logic/user_delete.php
Labels: Deprecation

#62 Add stock item page
  public/item.php
  public/views/logic/item_create.php
  public/views/logic/item_update.php
Labels: Enhancement, Admin

#63 [feat] added static file for inventory page
  public/css/styles.css
  public/inventory.php
Labels: Enhancement, Admin

#68 54 enhancementadmin improve user page
  public/user.php
  public/views/logic/user_add.php
  public/views/logic/user_admin_edit.php
  public/views/logic/user_delete.php
Labels: Enhancement, Admin

#66 [Feature] [Page] [Backend] Login Logout auth
  public/css/styles.css
  public/includes/auth.php
  public/includes/token.php
  public/login/index.php
  public/logout/index.php
Labels: Page, Feature

#72 Qr scanner
  public/admin/code/index.php
  public/admin/scanner/index.php
  public/admin/scanner/logic/payment.php
  public/admin/users/index.php
  public/admin/users/logic/user_add.php
  public/admin/users/logic/user_admin_edit.php
  public/css/styles.css
  public/includes/partial.php
Labels: Feature
